"""a test

Revision ID: 4898bd4219b1
Revises: 
Create Date: 2023-07-17 13:33:37.466609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4898bd4219b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_save',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('csv_content', sa.String(), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_save2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('csv_content_col1', sa.String(), nullable=True),
    sa.Column('csv_content_col2', sa.String(), nullable=True),
    sa.Column('csv_content_col3', sa.String(), nullable=True),
    sa.Column('csv_content_col4', sa.String(), nullable=True),
    sa.Column('csv_content_col5', sa.String(), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_files',
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file', flask_appbuilder.models.mixins.FileColumn(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=False),
    sa.Column('changed_by_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_files')
    op.drop_table('line')
    op.drop_table('csv_save2')
    op.drop_table('csv_save')
    # ### end Alembic commands ###
